apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-http01-cert
  namespace: cert-manager
spec:
  secretName: example-http01-cert-secret
  dnsNames:
    - "beepbop.cloud" # change this to your domain
  issuerRef:
    name: letsencrypt-http01-staging-clusterissuer
    kind: ClusterIssuer